version: '3.8'

services:
  # Evolution API - WhatsApp
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Server Config
      - NODE_ENV=production
      - SERVER_PORT=8080
      - SERVER_URL=https://evolution.${DOMAIN}
      
      # Logs
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_COLOR=true
      
      # Database - Conecta direto no Supabase
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=${SUPABASE_DB_URL}
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_api
      
      # Redis Local
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_TTL=604800
      - CACHE_LOCAL_ENABLED=false
      
      # Armazenamento
      - STORE_MESSAGES=true
      - STORE_MESSAGE_UP=true
      - STORE_CONTACTS=true
      - STORE_CHATS=true
      
      # Instance Config
      - INSTANCE_MAX_RETRY_QR=5
      - INSTANCE_EXPIRATION_TIME=false
      
      # Auth
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=false
      
      # Webhook Global
      - WEBHOOK_GLOBAL_URL=${WEBHOOK_GLOBAL_URL}
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=false
      
      # QRCode
      - QRCODE_LIMIT=30
      - QRCODE_COLOR=#10B981
      
      # Typebot/Chatwoot (desabilitado por padrão)
      - TYPEBOT_ENABLED=false
      - CHATWOOT_ENABLED=false
      
      # S3 (opcional para mídia)
      - S3_ENABLED=${S3_ENABLED:-false}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_BUCKET=${S3_BUCKET:-}
      - S3_PORT=${S3_PORT:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-}
      - S3_USE_SSL=${S3_USE_SSL:-true}
      
      # RabbitMQ (desabilitado, usando Redis)
      - RABBITMQ_ENABLED=false
      
      # WebSocket
      - WEBSOCKET_ENABLED=true
      - WEBSOCKET_GLOBAL_EVENTS=false
      
      # Configurações WhatsApp
      - WA_BUSINESS_TOKEN_WEBHOOK=false
      - WA_BUSINESS_URL=false
      - WA_BUSINESS_VERSION=v20.0
      - WA_BUSINESS_LANGUAGE=pt_BR
      
    volumes:
      - evolution-data:/app/instances
      - evolution-store:/app/store
    depends_on:
      - redis
    networks:
      - evolution-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis para Cache e Filas
  redis:
    image: redis:7-alpine
    container_name: evolution-redis
    restart: unless-stopped
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --maxmemory ${REDIS_MAX_MEMORY:-512mb}
      --maxmemory-policy ${REDIS_POLICY:-allkeys-lru}
      --appendonly ${REDIS_PERSISTENCE:-yes}
      --appendfsync ${REDIS_FSYNC:-everysec}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - evolution-network
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  evolution-data:
    driver: local
  evolution-store:
    driver: local
  redis-data:
    driver: local

networks:
  evolution-network:
    driver: bridge