version: '3.8'

services:
  # Evolution API - WhatsApp Multi-Instance
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution-api
    restart: unless-stopped
    # Sem portas expostas - Coolify gerencia via Traefik
    environment:
      # Configurações do Servidor
      - NODE_ENV=production
      - SERVER_PORT=8080
      - SERVER_URL=https://evolution.catalisti.com.br
      
      # Logs
      - LOG_LEVEL=info
      - LOG_COLOR=true
      
      # Banco de Dados - Supabase
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=${SUPABASE_DB_URL}
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_catalisti
      
      # Redis Cache Local
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CACHE_REDIS_PREFIX_KEY=evolution_catalisti
      - CACHE_REDIS_TTL=604800
      - CACHE_LOCAL_ENABLED=false
      
      # Configurações de Armazenamento
      - STORE_MESSAGES=true
      - STORE_MESSAGE_UP=true
      - STORE_CONTACTS=true
      - STORE_CHATS=true
      
      # Configurações de Instância
      - INSTANCE_MAX_RETRY_QR=5
      - INSTANCE_EXPIRATION_TIME=false
      
      # Autenticação
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=false
      
      # Webhook Global para seu App
      - WEBHOOK_GLOBAL_URL=${WEBHOOK_GLOBAL_URL}
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=false
      
      # QR Code
      - QRCODE_LIMIT=30
      - QRCODE_COLOR=#8B5CF6
      
      # Integrações (Desabilitadas)
      - TYPEBOT_ENABLED=false
      - CHATWOOT_ENABLED=false
      - OPENAI_ENABLED=false
      
      # S3 para Mídia (Opcional)
      - S3_ENABLED=${S3_ENABLED:-false}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_BUCKET=${S3_BUCKET:-evolution-catalisti}
      - S3_PORT=${S3_PORT:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-}
      - S3_USE_SSL=${S3_USE_SSL:-true}
      
      # RabbitMQ (Desabilitado - Usando Redis)
      - RABBITMQ_ENABLED=false
      
      # WebSocket
      - WEBSOCKET_ENABLED=true
      - WEBSOCKET_GLOBAL_EVENTS=false
      
      # Config WhatsApp Business
      - WA_BUSINESS_TOKEN_WEBHOOK=false
      - WA_BUSINESS_URL=false
      - WA_BUSINESS_VERSION=v20.0
      - WA_BUSINESS_LANGUAGE=pt_BR
      
    volumes:
      - evolution-instances:/app/instances
      - evolution-store:/app/store
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - coolify
    labels:
      # Labels para o Coolify
      - coolify.managed=true
      - coolify.type=application
      - coolify.name=Evolution API Catalisti
      - coolify.domain=evolution.catalisti.com.br
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis para Cache e Filas
  redis:
    image: redis:7-alpine
    container_name: evolution-redis
    restart: unless-stopped
    # Sem portas expostas - Comunicação interna apenas
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --appendfsync everysec
      --dir /data
      --dbfilename evolution-catalisti.rdb
    volumes:
      - redis-data:/data
    networks:
      - coolify
    labels:
      - coolify.managed=true
      - coolify.type=database
      - coolify.name=Redis Cache Catalisti
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --pass ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  evolution-instances:
    driver: local
  evolution-store:
    driver: local
  redis-data:
    driver: local

networks:
  coolify:
    external: true