version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    restart: unless-stopped
    environment:
      # Server Config
      - NODE_ENV=production
      - SERVER_PORT=8080
      - SERVER_URL=https://evolution.catalisti.com.br
      
      # Logs
      - LOG_LEVEL=info
      
      # Database - DESABILITAR MIGRATIONS
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=${SUPABASE_DB_URL}
      - DATABASE_SYNC_DB=false  # IMPORTANTE: Não rodar migrations
      
      # Redis
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://:${REDIS_PASSWORD}@redis:6379
      - CACHE_REDIS_PREFIX_KEY=evolution
      
      # Storage
      - STORE_MESSAGES=true
      - STORE_MESSAGE_UP=true
      - STORE_CONTACTS=true
      - STORE_CHATS=true
      
      # Auth
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      
      # Webhook
      - WEBHOOK_GLOBAL_URL=${WEBHOOK_GLOBAL_URL}
      - WEBHOOK_GLOBAL_ENABLED=true
      
    volumes:
      - evolution-instances:/evolution/instances
      - evolution-store:/evolution/store
    depends_on:
      - redis
    networks:
      - coolify
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:8080/healthcheck || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s  # Mais tempo para iniciar

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - coolify

volumes:
  evolution-instances:
  evolution-store:
  redis-data:

networks:
  coolify:
    external: true